import React from "react";

export default function Head() {
  return (
    <>
      <title>Frontend Mentor | Manage landing page</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="images/favicon-32x32.png"
      />
    </>
  );
}
